# Generated by Django 2.1.5 on 2020-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sicilian', 'Sicilian'), ('Regular', 'Regular')], default='Regular', max_length=8)),
                ('topping1', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini'), ('None', 'None')], default='None', max_length=25)),
                ('topping2', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini'), ('None', 'None')], default='None', max_length=25)),
                ('topping3', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini'), ('None', 'None')], default='None', max_length=25)),
                ('topping4', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini'), ('None', 'None')], default='None', max_length=25)),
                ('topping5', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini'), ('None', 'None')], default='None', max_length=25)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=5)),
            ],
        ),
    ]
