# Generated by Django 2.1.5 on 2020-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dinnerplatter_pasta_salad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=5),
        ),
    ]
