# Generated by Django 2.1.5 on 2020-04-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sub_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='salad',
            new_name='pasta',
        ),
    ]
