# Generated by Django 2.1.5 on 2020-04-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200422_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='salad',
            new_name='platter',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=5),
        ),
    ]
