# Generated by Django 3.0.5 on 2020-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200423_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='order',
            field=models.ManyToManyField(related_name='pizzas', to='orders.Order'),
        ),
    ]
