# Generated by Django 3.0.5 on 2020-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200423_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(related_name='orders', to='orders.Pizza'),
        ),
    ]
