# Generated by Django 3.0.5 on 2020-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200424_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
