# Generated by Django 3.0.5 on 2020-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzas', models.CharField(default='', max_length=10000)),
                ('salads', models.CharField(default='', max_length=10000)),
                ('pastas', models.CharField(default='', max_length=10000)),
                ('platters', models.CharField(default='', max_length=10000)),
                ('subs', models.CharField(default='', max_length=10000)),
                ('userid', models.IntegerField(default=0)),
                ('price', models.CharField(default='$0', max_length=10)),
            ],
        ),
    ]
