# Generated by Django 3.0.5 on 2020-04-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_completeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Received', max_length=20),
        ),
    ]
