# Generated by Django 3.0.5 on 2020-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_completeorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='pastas',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='pizzas',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='platters',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='salads',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='subs',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
